### ISSUE TITLE
Clarification on scope of Knapsacks.jl

### ISSUE THREAD

**Issue by jlchan** [rafaelmartinelli/KnapsackLib.jl#22]
Is there a list of types/variations of knapsack problems that Knapsacks.jl addresses? For example, does the package focus on the 0-1 traditional knapsack problem, or does it also address continuous knapsack problems and other variants?

I'm not that experienced in knapsack problems, so I couldn't tell for certain from the source code.

**Comment by rafaelmartinelli** [comment]
`DynamicProgramming`, `BinaryModel`, and `ExpandingCore` solve the 0-1 Knapsack, and `Heuristic` solves a sort of fractional Knapsack (probably without the last item), but only with integral input.

**Comment by jlchan** [comment]
Thank you!
